// From grbl/report.h
const ERROR_CODES = {
  1: 'Expected command letter',
  2: 'Bad number format',
  3: 'Invalid statement',
  4: 'Negative value',
  5: 'Setting disabled',
  6: 'Setting step pulse min',
  7: 'Setting read fail',
  8: 'Idle error',
  9: 'System GC lock',
  10: 'Soft limit error',
  11: 'Overflow',
  12: 'Max step rate exceeded',
  13: 'Check door',
  14: 'Line length exceeded',
  15: 'Travel exceeded',
  16: 'Invalid jog command',
  17: 'Setting disabled laser',
  20: 'GCode unsupported command',
  21: 'GCode modal group violation',
  22: 'GCode undefined feed rate',
  23: 'GCode command value not integer',
  24: 'GCode axis command conflict',
  25: 'GCode word repeated',
  26: 'GCode no axis words',
  27: 'GCode invalid line number',
  28: 'GCode value word missing',
  29: 'GCode unsupported coord sys',
  30: 'GCode G53 invalid motion mode',
  31: 'GCode axis words exist',
  32: 'GCode no axis words in plane',
  33: 'GCode invalid target',
  34: 'GCode arc radius error',
  35: 'GCode no offsets in plane',
  36: 'GCode unused words',
  37: 'GCode G43 dynamic axis error',
  38: 'GCode max value exceeded',
};

module.exports = {
  ERROR_CODES,
};
